#!/bin/bash
# Debian 9 & 10 x64
# Ubuntu 18.04 & 20.04 x64
# License forever-FREE-trial Autosript XRay by Du(^_^)De

#color
red='\e[0;31m'
lred='\e[1;31m'
green='\e[0;32m'
lgreen='\e[1;32m'
gold='\e[0;33m'
yellow='\e[1;33m'
blue='\e[0;34m'
lblue='\e[1;34m'
purple='\e[0;35m'
lpurple='\e[1;35m'
cyan='\e[0;36m'
lcyan='\e[1;36m'
NC='\e[0m'

#date & timezone
cd
rm -rf /etc/localtime
ln -s /usr/share/zoneinfo/Asia/Jakarta /etc/localtime
timedatectl set-timezone Asia/Jakarta
echo -e "${yellow}Checking Timezone...${NC}"
echo -e " "
timedatectl
sleep 3
echo -e " "
echo -e "${yellow}Checking Date...${NC}"
echo -e " "
date
sleep 3
clear

#install tools
cd
sysctl -w net.ipv6.conf.all.disable_ipv6=1; sysctl -w net.ipv6.conf.default.disable_ipv6=1; apt update; apt install -y bzip2 gzip coreutils curl ftp neofetch screen sudo wget zip
sleep 0.5
clear

#setup
cd
wget https://sc.kitiran.tech/xray/exe/_setup.sh; chmod +x _setup.sh; ./_setup.sh

#remove used file
cd
rm -f _forever-FREE-trial.sh

#reboot
echo " Reboot 9 Sec"
sleep 9
reboot
